version: 0.0
os: linux
files:
  - source: www
    destination: /var/www/html
  - source: codedeploy/apache/000-default.conf
    destination: /etc/apache2/sites-available
hooks:
  ApplicationStop:
    - location: codedeploy/app_stop.sh
      runas: root
  BeforeInstall:
    - location: codedeploy/cleanup_apache_conf.sh
      runas: root
  AfterInstall:
    - location: codedeploy/after_install.sh
      timeout: 180
  ApplicationStart:
    - location: codedeploy/app_start.sh
      runas: root
  ValidateService:
    - location: codedeploy/health_check.sh